# Generated by Django 4.2.6 on 2023-10-08 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
