# Generated by Django 4.2.6 on 2023-10-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='publicar',
            field=models.BooleanField(default=True),
        ),
    ]
